import logging
from telegram import Update
from telegram.ext import Application, CommandHandler, ContextTypes

# Enable logging
logging.basicConfig(
    format="%(asctime)s - %(name)s - %(levelname)s - %(message)s", level=logging.INFO
)
logger = logging.getLogger(__name__)

TOKEN = "8455111408:AAFG0doukDgec2jVBafKvzGOVTxnXLxeXCk"

# Start command
async def start(update: Update, context: ContextTypes.DEFAULT_TYPE):
    await update.message.reply_text("👋 Welcome!\nThis is your Temp Mail Bot.\n⚡ Generated by Shakil")

def main():
    app = Application.builder().token(TOKEN).build()

    # Command handler
    app.add_handler(CommandHandler("start", start))

    # Run bot
    app.run_polling()

if __name__ == "__main__":
    main()
