import json
import urllib.request
import time

BOT_TOKEN = "8455111408:AAFG0doukDgec2jVBafKvzGOVTxnXLxeXCk"
API_URL = f"https://api.telegram.org/bot{BOT_TOKEN}/"
user_data = {}

def send_message(chat_id, text, buttons=None):
    url = API_URL + "sendMessage"
    payload = {
        "chat_id": chat_id,
        "text": text,
        "parse_mode": "Markdown"
    }

    if buttons:
        payload["reply_markup"] = json.dumps({
            "inline_keyboard": buttons
        })

    headers = {"Content-Type": "application/json"}
    data = json.dumps(payload).encode("utf-8")
    req = urllib.request.Request(url, data=data, headers=headers)

    try:
        urllib.request.urlopen(req)
    except Exception as e:
        print("[Error] send_message:", e)

def get_updates(offset=None):
    url = API_URL + "getUpdates"
    if offset:
        url += f"?offset={offset}"
    try:
        with urllib.request.urlopen(url) as res:
            return json.loads(res.read())
    except Exception as e:
        print("[Error] get_updates:", e)
        return {}

def handle_command(message):
    chat_id = message["chat"]["id"]
    text = message.get("text", "")

    if text == "/start":
        buttons = [
            [{"text": "📧 Generate Email", "callback_data": "generate"}],
            [{"text": "📬 Inbox", "callback_data": "inbox"}],
            [{"text": "🗑 Delete Email", "callback_data": "delete"}],
            [{"text": "📊 Statistics", "callback_data": "statistics"}]
        ]
        send_message(chat_id, "👋 Welcome!\nThis is your Temp Mail Bot.\n⚡ Generated by Shakil", buttons)

def handle_callback(callback):
    chat_id = callback["message"]["chat"]["id"]
    data = callback["data"]
    user = user_data.get(chat_id)

    if data == "generate":
        email, token = create_email()
        if email:
            user_data[chat_id] = {"email": email, "token": token}
            send_message(chat_id, f"📧 Your email:\n`{email}`")
        else:
            send_message(chat_id, "⚠️ Could not generate email. Try again later.")
    elif data == "inbox":
        if not user:
            send_message(chat_id, "⚠️ Please generate an email first.")
        else:
            inbox = get_inbox(user["email"])
            if inbox:
                for msg in inbox:
                    sender = msg.get("from", "Unknown")
                    subject = msg.get("subject", "No Subject")
                    body = msg.get("body_text", "[No Body]")
                    message_text = f"📨 From: {sender}\n📌 Subject: {subject}\n💬 {body[:800]}"
                    send_message(chat_id, message_text)
            else:
                send_message(chat_id, "📭 Inbox is empty.")
    elif data == "delete":
        if chat_id in user_data:
            del user_data[chat_id]
            send_message(chat_id, "🗑 Email deleted.")
        else:
            send_message(chat_id, "⚠️ No email to delete.")
    elif data == "statistics":
        total = len(user_data)
        send_message(chat_id, f"📊 Total users with active emails: {total}")

def create_email():
    url = "https://api.internal.temp-mail.io/api/v3/email/new"
    data = json.dumps({"min_name_length": 10, "max_name_length": 10}).encode("utf-8")
    headers = {"Content-Type": "application/json", "accept": "application/json"}
    req = urllib.request.Request(url, data=data, headers=headers)
    try:
        with urllib.request.urlopen(req) as res:
            r = json.loads(res.read())
            return r["email"], r["token"]
    except Exception as e:
        print("[Error] create_email:", e)
        return None, None

def get_inbox(email):
    url = f"https://api.internal.temp-mail.io/api/v3/email/{email}/messages"
    headers = {"accept": "application/json"}
    req = urllib.request.Request(url, headers=headers)
    try:
        with urllib.request.urlopen(req) as res:
            return json.loads(res.read())
    except Exception as e:
        print("[Error] get_inbox:", e)
        return []

def answer_callback_query(callback_id):
    """Prevent duplicate triggers"""
    url = API_URL + "answerCallbackQuery"
    payload = {"callback_query_id": callback_id}
    data = json.dumps(payload).encode("utf-8")
    req = urllib.request.Request(url, data=data, headers={"Content-Type": "application/json"})
    try:
        urllib.request.urlopen(req)
    except:
        pass

def main():
    last_update_id = None
    print("🤖 Bot is running...")
    while True:
        updates = get_updates(last_update_id)
        for update in updates.get("result", []):
            if "message" in update:
                handle_command(update["message"])
            elif "callback_query" in update:
                handle_callback(update["callback_query"])
                answer_callback_query(update["callback_query"]["id"])

            # offset update must be last
            last_update_id = update["update_id"] + 1
        time.sleep(1)

if __name__ == "__main__":
    main()
